import os
import re
from datetime import date
import resend
from . import config


def _apply_inline_styles(html: str) -> str:
    replacements = [
        (
            r"<h2(?:\s[^>]*)?>",
            "<h2 style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 600; color: #1a1a1a; margin: 32px 0 12px; padding: 0;\">",
        ),
        (
            r"<p(?:\s[^>]*)?>",
            "<p style=\"font-family: Georgia, 'Times New Roman', serif; font-size: 15px; line-height: 1.75; color: #333; margin: 0 0 16px;\">",
        ),
        (
            r"<ul(?:\s[^>]*)?>",
            '<ul style="padding-left: 20px; margin: 0 0 16px;">',
        ),
        (
            r"<li(?:\s[^>]*)?>",
            "<li style=\"font-family: Georgia, 'Times New Roman', serif; font-size: 15px; line-height: 1.75; color: #333; margin-bottom: 6px;\">",
        ),
        (
            r"<strong(?:\s[^>]*)?>",
            '<strong style="color: #1a1a1a;">',
        ),
    ]
    for pattern, replacement in replacements:
        html = re.sub(pattern, replacement, html)
    html = re.sub(
        r"(<h2[^>]*>Competitive Digest</h2>)",
        r'<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 36px 0;">\1',
        html,
        flags=re.IGNORECASE,
    )
    return html


def _sources_html(results: list[dict]) -> str:
    parts = []
    for r in results:
        if not r.get("sources"):
            continue
        links = "".join(
            f'<a href="{url}" style="color: #999; font-size: 12px; '
            f"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; "
            f'text-decoration: none; display: block; margin-bottom: 4px; word-break: break-all;">'
            f"{url}</a>"
            for url in r["sources"][:3]
        )
        parts.append(
            f'<p style="font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif; '
            f'font-size: 11px; font-weight: 600; color: #bbb; letter-spacing: 0.07em; '
            f'text-transform: uppercase; margin: 0 0 6px;">{r["company"]} Sources</p>'
            f"{links}"
            f'<div style="margin-bottom: 20px;"></div>'
        )
    return "\n".join(parts)


def send(html_content: str, companies: list[str], results: list[dict] | None = None) -> None:
    resend.api_key = os.environ["RESEND_API_KEY"]

    subject_companies = ", ".join(companies)
    subject_date = date.today().strftime("%B %d, %Y")
    companies_display = " &middot; ".join(companies)

    styled_content = _apply_inline_styles(html_content)
    sources_block = (
        f'<div style="padding: 24px 36px 20px; border-top: 1px solid #efefef; background-color: #fafafa;">'
        f"{_sources_html(results)}"
        f"</div>"
        if results
        else ""
    )

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="background-color: #f5f5f5; margin: 0; padding: 32px 16px;">
  <div style="max-width: 640px; margin: 0 auto; background-color: #ffffff; border-radius: 6px; border: 1px solid #e4e4e4; overflow: hidden;">

    <div style="background-color: #f7f7f7; padding: 28px 36px 24px; border-bottom: 1px solid #e8e8e8;">
      <p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 11px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; color: #aaa; margin: 0 0 8px;">Competitor Digest</p>
      <p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 22px; font-weight: 700; color: #1a1a1a; margin: 0 0 6px; line-height: 1.3;">{companies_display}</p>
      <p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 13px; color: #999; margin: 0;">{subject_date}</p>
    </div>

    <div style="padding: 32px 36px 28px;">
      {styled_content}
    </div>

    {sources_block}

    <div style="padding: 16px 36px; border-top: 1px solid #efefef;">
      <p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 11px; color: #ccc; margin: 0;">Generated by Competitor Digest</p>
    </div>

  </div>
</body>
</html>"""

    params: resend.Emails.SendParams = {
        "from": "onboarding@resend.dev",
        "to": [config.TO_EMAIL],
        "subject": f"Competitor Digest: {subject_companies} — {subject_date}",
        "html": html,
    }
    resend.Emails.send(params)
